import { useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { BookMarked, CheckCircle2, Loader2, Mic2, Save, Volume2 } from 'lucide-react';
import AiChatbot from '../components/AiChatbot.jsx';
import ProgressRing from '../components/ProgressRing.jsx';
import Visualizer from '../components/Visualizer.jsx';
import { findTopic } from '../data/topics.js';
import { askAi, saveProgress } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';

export default function Learn() {
  const { topicId } = useParams();
  const topic = findTopic(topicId);
  const { user } = useAuth();
  const [explanation, setExplanation] = useState('');
  const [notes, setNotes] = useState('');
  const [completed, setCompleted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const progress = useMemo(() => completed ? 100 : Math.min(85, 25 + notes.length * 2), [completed, notes.length]);

  useEffect(() => {
    if (!topic) return;
    let active = true;
    setLoading(true);
    askAi({
      topic: topic.title,
      mode: 'explain',
      question: `Explain ${topic.title} for a data structures learner. Include intuition, operations, complexity, and one real-world example.`
    })
      .then((response) => active && setExplanation(response.answer))
      .catch(() => active && setExplanation(topic.description))
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, [topic]);

  if (!topic) return <Navigate to="/" replace />;

  const speak = () => {
    const utterance = new SpeechSynthesisUtterance(explanation || topic.description);
    utterance.rate = 0.95;
    utterance.pitch = 1;
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  };

  const handleSave = async () => {
    setSaving(true);
    await saveProgress({ userId: user.uid, topicId: topic.id, completed, notes });
    setSaving(false);
  };

  const markComplete = async () => {
    setCompleted(true);
    await saveProgress({ userId: user.uid, topicId: topic.id, completed: true, notes });
  };

  return (
    <div className="page learn-page">
      <section className="learn-header" style={{ '--accent': topic.accent }}>
        <div>
          <span className="eyebrow">{topic.level} module</span>
          <h1>{topic.title}</h1>
          <p>{topic.description}</p>
        </div>
        <ProgressRing value={progress} label="module progress" />
      </section>

      <section className="learn-grid">
        <div className="learning-panel visualizer-panel">
          <div className="panel-heading">
            <BookMarked size={20} />
            <div>
              <h2>3D Visualizer</h2>
              <p>Drag, zoom, and run the operation controls.</p>
            </div>
          </div>
          <Visualizer type={topic.visualizer} />
        </div>

        <div className="learning-panel">
          <div className="panel-heading">
            <Mic2 size={20} />
            <div>
              <h2>AI Explanation</h2>
              <p>Generated by Gemini through the Flask API.</p>
            </div>
          </div>
          {loading ? (
            <div className="loading-line"><Loader2 className="spin" size={18} /> Generating explanation...</div>
          ) : (
            <p className="ai-explanation">{explanation}</p>
          )}
          <button className="ghost-button" type="button" onClick={speak} disabled={!explanation}>
            <Volume2 size={17} /> Voice explanation
          </button>
        </div>
      </section>

      <section className="learn-grid bottom">
        <div className="learning-panel">
          <div className="panel-heading">
            <Save size={20} />
            <div>
              <h2>Notes</h2>
              <p>Saved with your topic progress.</p>
            </div>
          </div>
          <textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Write your mental model, edge cases, or questions..." />
          <div className="row-actions">
            <button className="ghost-button" onClick={handleSave} disabled={saving}>{saving ? 'Saving...' : 'Save notes'}</button>
            <button className="primary-button" onClick={markComplete}><CheckCircle2 size={17} /> Mark complete</button>
            <Link className="primary-button" to={`/quiz/${topic.id}`}>Take quiz</Link>
          </div>
        </div>
        <AiChatbot topic={topic} />
      </section>
    </div>
  );
}
